### ISSUE TITLE
Error when physgunning

### ISSUE THREAD

**Issue by TheRealButteredToast** [rebel1324/CityRP#1]
This error pops up whenever I physgun a prop or entity
[ERROR] gamemodes/halorp/schema/sh_hooks.lua:197: attempt to call method 'CPPIGetOwner' (a nil value)
  1. unknown - gamemodes/halorp/schema/sh_hooks.lua:197
   2. unknown - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:420

**Comment by rebel1324** [comment]
put all addons in the github.
