### ISSUE TITLE
Error when making another faction in city rp

### ISSUE THREAD

**Issue by OhTanoshi** [rebel1324/CityRP#12]
At first, i thought it was the player models i was using but changed the models to the defult citizen ones and still had this error 

[ERROR] gamemodes/cityrp/plugins/cityrphud.lua:101: attempt to index local 'classData' (a nil value)
  1. unknown - gamemodes/cityrp/plugins/cityrphud.lua:101
   2. unknown - gamemodes/nutscript/gamemode/core/libs/sh_plugin.lua:420

**Comment by rebel1324** [comment]
Well, I didn't made this CityRP gamemode for multiple factions.

**Comment by OhTanoshi** [comment]
Is there any way to get around it to add a faction?

**Comment by OhTanoshi** [comment]
Easy fix to multiple factions on CityRP is to make sure both new classes and factions have unique names.
