### ISSUE TITLE
Multiple entities dont work

### ISSUE THREAD

**Issue by OhTanoshi** [rebel1324/CityRP#14]
[ERROR] gamemodes/cityrp/entities/entities/moneyprinter_lg/init.lua:20: Tried to use a NULL physics object!
  1. Wake - [C]:-1
   2. unknown - gamemodes/cityrp/entities/entities/moneyprinter_lg/init.lua:20
    3. Spawn - [C]:-1
     4. onRun - gamemodes/cityrp/schema/sh_commands.lua:431
      5. run - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:159
       6. parse - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:204
        7. unknown - gamemodes/nutscript/gamemode/core/libs/sh_command.lua:240
         8. func - gamemodes/nutscript/gamemode/core/libs/thirdparty/sh_netstream2.lua:117
          9. unknown - lua/includes/extensions/net.lua:32

The fod vender, microwaves and more dont work either.

we do have all content in the server so not 1000 percent sure whats causing it

**Comment by rebel1324** [comment]
Check your Contents Pack
