### ISSUE TITLE
Pac error

### ISSUE THREAD

**Issue by OhTanoshi** [rebel1324/CityRP#15]
[ERROR] addons/pac3/lua/pac3/core/client/base_part.lua:1019: attempt to index field 'last_owner' (a nil value)
  1. HookEntityRender - addons/pac3/lua/pac3/core/client/base_part.lua:1019
   2. v - addons/pac3/lua/pac3/core/client/base_part.lua:286
    3. v - addons/pac3/lua/pac3/core/client/drawing.lua:550
     4. unknown - lua/includes/modules/hook.lua:84

this is made when items are wore and a player dies

**Comment by rebel1324** [comment]
This goes to rebel1324/Nutscript
