### ISSUE TITLE
Door System UI

### ISSUE THREAD

**Issue by Sampleeeee** [rebel1324/CityRP#25]
Hello, The door system UI seems to show up on the inside of the door on some maps and the text is really small, example: http://steamcommunity.com/sharedfiles/filedetails/?id=1325718706
Thank you for your time

**Comment by Sampleeeee** [comment]
Also, I can't seem to find the content pack anywhere for this, almost every playermodel is an error (i do have css)

**Comment by OmarAssadi** [comment]
Late response, I know. But, you can find the citizen content here: https://steamcommunity.com/workshop/filedetails/?id=1083149622

And, the printer content is here: https://steamcommunity.com/sharedfiles/filedetails/?id=597570090

**Comment by rebel1324** [comment]
This is something that I can't help because some door brushes are not placed correctly.
