### ISSUE TITLE
TFA weapon Errors on shooting

### ISSUE THREAD

**Issue by ItsAJokeGmod** [rebel1324/CityRP#4]
[ERROR] gamemodes/cityrp/plugins/tfasupport/cl_effects.lua:33: attempt to index field 'emitter' (a nil value)
  1. FixedParticle - gamemodes/cityrp/plugins/tfasupport/cl_effects.lua:33
   2. unknown - gamemodes/cityrp/plugins/tfasupport/cl_effects.lua:171
    3. Effect - [C]:-1
     4. ShootEffectsCustom - lua/weapons/tfa_gun_base/sh_effects.lua:238
      5. unknown - lua/weapons/tfa_gun_base/shared.lua:1190

[ERROR] gamemodes/cityrp/plugins/tfasupport/cl_effects.lua:183: bad argument #1 to 'ipairs' (table expected, got nil)
  1. ipairs - [C]:-1
   2. unknown - gamemodes/cityrp/plugins/tfasupport/cl_effects.lua:183

**Comment by nateabowman** [comment]
Issue was never fixed.

**Comment by rebel1324** [comment]
Stil same error appears? TFA SV Edition is not gonna work.

**Comment by nateabowman** [comment]
I'm using https://steamcommunity.com/sharedfiles/filedetails/?id=415143062

**Comment by lechu2375** [comment]
Still broken.

**Comment by nateabowman** [comment]
I removed part of it until its fixed.
