### ISSUE TITLE
Models missing

### ISSUE THREAD

**Issue by KaiNW** [rebel1324/CityRP#40]
So, I've managed to decide for NutScript because of its natural beauty, I checked out CityRP and its working for the most part, however at the moment i'm stuck with missing models for things like the moneyprinter.

So where do I find those?

#Edit: The moneyprinters are missing for the most part.

**Comment by OmarAssadi** [comment]
Hey, try these: https://steamcommunity.com/sharedfiles/filedetails/?id=597570090

**Comment by KaiNW** [comment]
Thanks, that helped partly!

I'm still missing the casino thing along with the Security things

**Comment by rebel1324** [comment]
@Saxithon Some of the models are not included because of they're paid addons.
